#!/usr/bin/env python3
"""Rasterizes printable ASCII from the Hack font into media/src/render/overlay_font.h.

Run once when the overlay font needs to change:
    python3 scripts/gen-overlay-font.py /usr/share/fonts/source-foundry-hack-fonts/Hack-Bold.ttf
Hack: MIT License + Bitstream Vera License (see THIRD-PARTY.md).
"""
import sys
from PIL import Image, ImageDraw, ImageFont

src = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/fonts/source-foundry-hack-fonts/Hack-Bold.ttf'
out = sys.argv[2] if len(sys.argv) > 2 else 'media/src/render/overlay_font.h'
SIZE = 15
font = ImageFont.truetype(src, SIZE)
asc, desc = font.getmetrics()
cell_h = asc + desc
cell_w = int(max(font.getbbox(chr(c))[2] for c in range(32, 127)))
cell_w = int(max(cell_w, round(font.getlength("M"))))

glyphs = []
for c in range(32, 127):
    img = Image.new('L', (cell_w, cell_h), 0)
    ImageDraw.Draw(img).text((0, 0), chr(c), font=font, fill=255)
    glyphs.append(img.tobytes())

with open(out, 'w') as f:
    f.write('// Generated by scripts/gen-overlay-font.py from the Hack font (MIT + Bitstream Vera\n')
    f.write('// License, see THIRD-PARTY.md). 8-bit alpha, one byte per pixel, ASCII 32..126.\n')
    f.write('#pragma once\n#include <cstdint>\n\nnamespace ps {\n')
    f.write(f'constexpr int kOverlayGlyphW = {cell_w};\nconstexpr int kOverlayGlyphH = {cell_h};\n')
    f.write(f'constexpr int kOverlayFirstChar = 32;\nconstexpr int kOverlayGlyphCount = {len(glyphs)};\n')
    f.write('constexpr uint8_t kOverlayFont[] = {\n')
    for g in glyphs:
        f.write('  ' + ','.join(str(b) for b in g) + ',\n')
    f.write('};\n}  // namespace ps\n')
print(f'{out}: {len(glyphs)} glyphs {cell_w}x{cell_h}')
